version: '3'
services:
  telegram-bot:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    environment:
      - MONGO_DB_URL=mongodb://mongodb:27017/
      - MONGO_DB=vpn_bot

      - TELEGRAM_TOKEN=5854895024:AAEFFw548ac5MRXnOpbuYsoU9a-OOatBdOk
      - SUBSCRIPTION_PRICE=2

      - WIREGUARD_URL=http://wg-easy:51821
      - WIREGUARD_PASSWORD=2432546Wg

      - WALLET_TOKEN=4100118145719086.18141EF20A6D0D082CEB490FCD456B3B2AD067F15A33218A79FF8256EFEE605AA67C6B26CD484C50326FEC87DF75F2DE46267D457C70198ADD69EC3B8D54225426AE1F16C77D2A9F1FFEE891807B6DD291BAB5D1E53E610201FA1AACE82356FB44EE8651FCBEB2922466EC6298F8FA0C59D503D40AE0B4F840503DD7A3E0C0C1

    ports:
      - 8443:8443

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  wg-easy:
    image: weejewel/wg-easy
    container_name: wg-easy
    environment:
      - WG_HOST=127.0.0.1
      - PASSWORD=2432546Wg
    volumes:
      - ~/.wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
